### ISSUE TITLE
Fatal error: cannot autowire service

### ISSUE THREAD

**Issue by stanislav-janu** [nette/coding-standard#34]
Version 2.1.1 not working everywhere (tried on localhost and Gitlab CI).

## Error
```
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Symplify\TokenRunner\DocBlock\DescriptionAnalyzer": argument "$typeNodeAnalyzer" of method "__construct()" references class "Symplify\BetterPhpDocParser\PhpDocParser\TypeNodeAnalyzer" but no such service exists. in /builds/project-0/temp/nette-coding-standard/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:54
Stack trace:
#0 /builds/project-0/temp/nette-coding-standard/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(82): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /builds/project-0/temp/nette-coding-standard/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /builds/project-0/temp/nette-coding-standard/vendor/symfony/de in /builds/project-0/temp/nette-coding-standard/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php on line 54
```

## CI config.
```
code_standard:7.3:
    image: php:7.3
    before_script:
        - apt-get update
        - apt-get install zip unzip -y
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php composer-setup.php
        - php -r "unlink('composer-setup.php');"
        - php composer.phar install --ignore-platform-reqs --no-interaction --no-progress
        - if [ -z "$CI_PROJECT_PATH" ]; then CI_PROJECT_PATH="project-0";fi
        - php composer.phar create-project nette/coding-standard /builds/$CI_PROJECT_PATH/temp/nette-coding-standard
    script:
        - php -d memory_limit=512M /builds/$CI_PROJECT_PATH/temp/nette-coding-standard/ecs check app tests --config /builds/$CI_PROJECT_PATH/temp/nette-coding-standard/coding-standard-php71.yml
```

## On localhost I run
```
composer create-project nette/coding-standard temp/nette-coding-standard

php -d memory_limit=512M temp/nette-coding-standard/ecs check app tests --config vendor/nette/coding-standard/coding-standard-php71.yml
```
